[package]
name = "screenrec"
version = "0.1.0"
edition = "2024"

[dependencies]
scrap = "0.5.0"
image = "0.24"
ctrlc = "3.5"
nix = { version = "0.27", features = ["signal"] }

[[bin]]
name="fps_test"
path="src/tests/scrap_fps.rs"